{
  "hash": "5ef0145052b1eb8526ddd18956e30d31",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Jack mackerel management strategy evaluation for SC14\"\nsubtitle: \"Operating models, candidate management procedures, robustness tests, and matters for Scientific Committee consideration\"\ndate: 2026-08-09\ndate-format: \"[Working revision based on SC14-MSE-2026-RC1 —] D MMMM YYYY\"\nlanguage:\n  title-block-published: \"\"\nbibliography: sc14-mse-report.bib\nnocite: |\n  @*\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    embed-resources: false\n    lightbox: true\n    format-links: false\n  pdf:\n    include-in-header:\n      - ../_includes/sc14-pdf-header.tex\n      - ../_includes/sc14-pdf-cover.tex\nheader-includes:\n  - '\\renewcommand{\\SCdocumentnumber}{SC14-JM07}'\n  - '\\renewcommand{\\SCshorttitle}{Jack mackerel MSE}'\n  - '\\renewcommand{\\SCcovertitle}{Jack mackerel management strategy evaluation for SC14}'\n  - '\\renewcommand{\\SCcoverfootnoteoffset}{2.5in}'\n---\n\n```{=html}\n<div class=\"sprfmo-front\">\n  <div class=\"sprfmo-banner\">\n    <h1 class=\"sprfmo-wordmark\">SPRFMO</h1>\n    <div class=\"sprfmo-subtitle\">South Pacific Regional Fisheries Management Organisation</div>\n    <div class=\"sprfmo-rule\"></div>\n    <div class=\"sprfmo-group\">Jack Mackerel Candidate Management Procedures</div>\n  </div>\n</div>\n```\n\n\n::: {.content-visible when-format=\"html\"}\n[Download the PDF version](sc14-mse-report.pdf){.btn .btn-primary}\n:::\n\n<div class=\"paper-title\">Jack Mackerel Management Strategy Evaluation: Synthesis for SC14</div>\n\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<div id=\"sc14-release-stamp\" class=\"draft-stamp\" aria-label=\"Report release candidate and date\"></div>\n<script>\n(() => {\n  const source = document.querySelector(\"#title-block-header .date\");\n  const target = document.getElementById(\"sc14-release-stamp\");\n  if (source && target) target.textContent = source.textContent.trim();\n})();\n</script>\n```\n:::\n\n::: {.status-note}\n**Status and purpose.** This is a working pre-submission revision based on the\nscientific outputs frozen in `SC14-MSE-2026-RC1`. The revised documents and\nnew review-evidence tables are not part of that fingerprinted release; they\nrequire a new release candidate after review. The report synthesizes the June\n2026 SCW17 MSE workshop and subsequent model and management-procedure\ndevelopment.\n:::\n\n## Executive summary {.unnumbered}\n\nThe jack mackerel MSE has progressed from a broad workshop design into a\nnarrower comparison of candidate management procedures (CMPs) tested against a\nreference operating model (OM) and a structured set of robustness OMs. SCW17\nestablished the principal design choices: simple and interpretable empirical\nrules, simulation of correlated index errors, dynamic reference points,\nexplicit robustness testing, a broad performance-measure set, and development\nof an exceptional-circumstances protocol. Post-workshop work corrected and\nextended the implementation, tuned the leading rule families, and examined\ntheir performance under one-stock and two-stock hypotheses, recruitment\nstress, movement, selectivity, and alternative annual TAC-change limits.\n\nA novel feature of this MSE is its treatment of the five abundance indicators\nas related observations rather than independent sources of information. The OMs\nsimulate their observation errors jointly using historical estimates of each\nseries' uncertainty, temporal autocorrelation, and cross-correlation. This\nallows the evaluation to represent shared movements among indicators,\nincluding correlation that may arise when the population shifts spatially.\nThe estimated correlation structure used for the reference OM is illustrated\nin @fig-om11-index-error-correlations.\n\nAmong the dozens of MPs evaluated at the SCW17 workshop, the analysts concluded\nthat the hockey-stick and power-ramp designs represented by these two CMPs,\ntogether with reasonable variants of those designs, were suitable to carry\nforward as proposals for consideration at SC14. This analytical conclusion\nidentifies a focused set for Scientific Committee consideration; it is not a\nformal recommendation or adoption decision.\n\nThe [main Jack Mackerel MSE resource\npage](https://sprfmo.github.io/jmMSE26/) describes the naming conventions and\nhow the MSE components fit together, and provides the CMP and OM registries and\ntranslation tables linking the labels used across analyses and reports.\n\nTwo CMPs are the focal cases for the current comparison:\n\n- **HS-20 (MP43)** uses a hockey-stick harvest control rule (HCR), a 2,000-kt\n  catch target, a 270-kt minimum, and annual limits of a 20% decrease and 15%\n  increase.\n- **PR-20 (MP44)** uses a power-ramp HCR, a 1,500-kt catch target, the same\n  minimum, and the same annual limits, with a more responsive reduction in\n  advice as the indicator declines, and the ability to increase catches above\n  the target level.\n\nBoth use the combined indicator assembled from five standardized abundance indices.\nThe earlier **HS+20 (MP29)** and **PR+20 (MP32)** specifications are retained\nas sensitivity cases. They arose from an initial request informed by early\nfeedback from Chile's internal MSE research project; their 20% maximum annual\nTAC increase was not selected from the later Commission poll. That poll helped\ninform the broader set of annual TAC-change variants examined here. The\nremaining **HSsym**, **HS-30**, **PRsym**, and **PR-30** procedures are\nadditional comparison cases. The paired catch trajectories for focal HS-20\nand sensitivity HS+20 illustrate one annual-limit contrast in\n@fig-catch-spaghetti.\n\nThe scorecard is retained as a preliminary sensitivity tool rather than an\nexecutive ranking. Its ordering changes with the candidate set, metrics,\ndirections, scaling, and weights; it does not determine biological\nacceptability, focal status, or a shortlist. Raw outcomes, uncertainty, and\nperformance under individual OMs remain the primary evidence.\n\nAll eight CMPs were refined against the same 500 posterior draws to target an\napproximately 60% mean probability of dynamic Kobe-green status during\n2041--2050. Their realized probabilities range from 59.2% to 61.0%, so the\ncomparison is now like-for-like with respect to the tuning objective. The\narchived 100-draw results remain useful provenance but are superseded by the\n500-draw reference and robustness results used throughout this report. The\nearlier comparisons reviewed on 24 July identified a broad contrast between\nthe stability of the hockey-stick family and the stronger response of the\npower-ramp family as indicators declined. The completed results refine that\ncomparison across all eight CMPs; differences depend on the OM and performance\nmeasure and do not establish a preferred or \"optimal\" CMP.\n\nThe most consequential robustness finding came from the two-stock hypotheses.\nWithout movement, the southern component passed the agreed benchmark while the\nnorthern component required an exploratory change of ~3% in simulated catch\ndistribution from north to south to reach the same\nbenchmark. This is a sensitivity result, not an allocation recommendation.\nWith movement, no tested fixed catch distribution achieved the long-term\nbenchmark for both components. Equal weighting of indices could also mask a\ndeclining southern component when northern indices increased. Separate annual\ntracking of northern and southern indices is therefore an important candidate\nelement of exceptional-circumstances monitoring.\n\nThe Scientific Committee is asked to consider the adequacy of HS-20 (MP43) and\nPR-20 (MP44) as the focal cases; the role of HS+20 (MP29) and PR+20 (MP32) as\nsensitivity cases; the other annual TAC-change variants to retain;\nthe role of all five indices, including the only fishery-independent series;\nthe interpretation of two-stock robustness; the completed 500-draw reference\nand robustness evaluation; and the work needed\nto validate and complete banking-and-borrowing and\nexceptional-circumstances evaluation.\n\n## Purpose, scope, and decision status\n\nThe MSE is intended to compare complete management procedures in a closed-loop\nsimulation before one is considered for implementation. Each CMP converts\nagreed observations into annual catch advice; each OM represents a plausible\ndescription of stock and fishery dynamics against which the CMP is tested.\nPerformance measures describe biological outcomes, yield, stability, and\nfishery feasibility over specified periods.\n\nThis report melds the technical foundation assembled in the\n[benchmark-preparation and MSE-planning materials](https://sprfmo.github.io/JM_SCW_prep/),\nthe design record from the\n[SCW17 MSE Workshop report](https://sprfmo.github.io/scw17/SCW17-MSE-Workshop-report.html),\nand the post-workshop analysis summarized in the\n[final 24 July task-team meeting report](https://sprfmo.github.io/jmMSE26/outputs/meeting-report-20260724/SC14_JM_MSE_meeting_report_2026-07-24.pdf)\nand the [presentation from Wageningen Marine Research consultants\n(WUR)](presentation_20260725.pdf).\nThe preparation site preceded SCW17 and\nprovided the detailed model specifications, diagnostics, working papers, and\ntechnical discussions needed to update the operating models used at SCW17 and\nin subsequent MSE work. Their different roles are summarized in\n@tbl-source-roles.\n\n| Source | Role in this synthesis |\n|:---|:---|\n| [Benchmark preparation and MSE planning](https://sprfmo.github.io/JM_SCW_prep/) | Pre-SCW17 benchmark papers, OM specifications, diagnostics, index analyses, and preparatory meeting records that supported updates to the OMs used at SCW17 and beyond. |\n| [SCW16 benchmark report](https://sprfmo.github.io/JM_SCW_prep/JMWG-Benchmark-Meeting-report-2026.html) | Formal record of the May 2026 benchmark review, including assessment inputs, abundance indices, biological assumptions, model alternatives, decisions, and uncertainties to carry into OM conditioning. |\n| [SCW17/Paper-01: Model developments](https://sprfmo.github.io/scw17/SCW17-Paper-01-ModelDevelopments.html) | Post-SCW16, pre-SCW17 bridge from the benchmark model sequence to the `0.15` and `0.16` configurations considered for MSE conditioning, with model comparisons and diagnostics. |\n| SCW17 workshop report, 15--19 June 2026 | Agreed MSE design, OM and CMP principles, reference-point approach, performance framework, and planned robustness work. |\n| Post-workshop `jmMSE` analysis | Implemented CMP definitions, tuning runs, reference and robustness simulation outputs, and reproducibility records. |\n| Task-team meeting, 24 July 2026 | Interpretation of results, wording cautions, issues for SC14, and agreed follow-up. |\n| [July WUR presentation](presentation_20260725.pdf) | Detailed tuning sequence, OM contrasts, and graphical robustness diagnostics available at the time of review. |\n| Draft weighted scorecard, 23 July 2026 | Example of an editable multi-criteria comparison method; not an exhaustive candidate list, metric list, or decision. |\n\n: Source materials and their roles in this synthesis. {#tbl-source-roles}\n\nThe Scientific Committee provides scientific advice and the Commission weighs\nmanagement trade-offs and makes management decisions. A shortlist in an MSE\nanalysis is not an adoption decision.\n\n## Development from SCW17 to the current analysis\n\nSCW17 continued work begun at the\n[2025 SCW15 MSE workshop](https://sprfmo.github.io/SCW15_report/)\n[@sprfmo2025scw15] and the 2026 benchmark. The\n[benchmark-preparation and MSE-planning site](https://sprfmo.github.io/JM_SCW_prep/)\npreserves the detailed model specifications, diagnostics, index working\npapers, and preparatory meeting discussions that preceded SCW17. That record\nprovided the technical basis for updating the operating models taken into the\nworkshop and used in subsequent MSE analyses.\n\nSCW17 aimed to prepare an OM set, trial CMPs, performance statistics,\nrobustness scenarios, and documentation for SC14. The workshop favored simple\nempirical rules because they are transparent, reproducible, and can be locked\nbefore use. Trial CMPs were used to learn about rule behavior and were not\nfinal recommendations.\n\nPost-workshop work made the following material advances:\n\n1. Index projection errors were extended to include iteration-specific\n   variability, autocorrelation, and cross-correlation among index deviations.\n2. Dynamic biological reference points and additional measures, including\n   vulnerable-biomass and exploitation measures, were incorporated.\n3. A straight-slope comparison rule was added.\n4. The power-ramp implementation was corrected to remove discontinuities around\n   its limit. The correction was required for consistent implementation but did\n   not overturn the broad workshop conclusions.\n5. A projected effort constraint was added to avoid implausible catches that\n   would require extreme effort increases from current levels.\n6. CMP tuning was performed as a nested screen of HCR family, catch target,\n   minimum catch, index limit, index set, simulation replication, and robustness\n   performance.\n7. Alternative annual TAC-change limits were retuned instead of being compared\n   using triggers tuned under a different constraint.\n\nThe development of vulnerable-biomass performance indicators responded to a\nrequest from SCW17 for a measure that could complement spawning biomass and be\nmore relatable to fishers. In this context, vulnerable biomass represents the\nfish available to the fishing fleet under the modeled selectivity. It was\ntherefore developed as a fishery-facing performance measure, while spawning\nbiomass remains the principal measure of reproductive stock condition.\n\nThe July WUR presentation used the word \"optimal\" for some within-family runs.\nThe 24 July meeting clarified the interpretation: those runs were useful\nwithin-family representatives, but the analysis does not establish an optimal\nprocedure across management objectives.\n\nThe sequence from the workshop trials to the current comparison is recorded in\n[`candidate-development-history.csv`](../data/candidate-development-history.csv).\nThe workshop `run18`/`run20`/`run22` subset is an antecedent development set,\nnot a one-to-one renaming of MP29/MP32 or MP43--MP48. The annual-limit variants\nwere added after the 24 July meeting and remain analyst-developed comparison\ncases awaiting Task Team and Scientific Committee review.\n\n\n::: {#tbl-candidate-history .cell tbl-cap='Development and decision status of the current CMP comparison.'}\n::: {.cell-output-display}\n\n\n|Stage                           |Date               |Identifiers                                    |Material change                                                                                                                                                 |Decision status                                                                                        |\n|:-------------------------------|:------------------|:----------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------|\n|SCW17 Day 4                     |2026-06-18         |run18; run20; run22                            |Retained a high-target base case, a minimum-catch case, and a special-shape case from the broader workshop trials                                               |Selected by the workshop for post-workshop robustness testing; not a final CMP selection               |\n|Post-workshop family refinement |2026-06 to 2026-07 |MP16; MP25; MP29; MP32                         |Added the five-index combination, corrected the power-ramp implementation, adopted the 2019-2023 reference period, and refined minimum and index-limit settings |Analytical development; the workshop run identifiers do not map one-to-one to the later MP identifiers |\n|Task-team interpretation        |2026-07-24         |MP29; MP32                                     |Recorded the stability-responsiveness contrast and remaining work; avoided treating within-family representatives as globally optimal                           |Draft meeting record; did not select a final CMP                                                       |\n|Annual-limit comparison         |after 2026-07-24   |MP43-MP48                                      |Added reverse-asymmetric, symmetric, and 30-percent-decrease limits; each variant received its own trigger                                                      |Analyst-added comparison awaiting Task Team and Scientific Committee review                            |\n|Common 500-draw refinement      |2026-08            |MP29; MP43; MP45; MP47; MP32; MP44; MP46; MP48 |Retuned all eight controls with the same 500 posterior draws and ran the reference plus nine robustness OMs                                                     |Complete analytical comparison; roles are focal, sensitivity, or comparison cases, not a shortlist     |\n|Named SC14 release candidate    |2026-08-09         |SC14-MSE-2026-RC1                              |Aligned CMP registry, results, figures, scorecards, downloads, Slick contents, papers, run list, and file fingerprints                                          |All automatic agreement checks passed; SC14 decision remains outstanding                               |\n\n\n:::\n:::\n\n\n## Operating models and simulation methods\n\n### Reference and robustness set\n\nThe operating-model set did not begin at SCW17. The\n[SCW16 benchmark workshop report](https://sprfmo.github.io/JM_SCW_prep/JMWG-Benchmark-Meeting-report-2026.html)\nrecords the 18--22 May 2026 review of assessment inputs, abundance indices,\nbiological assumptions, assessment-model alternatives, and priorities for OM\nconditioning [@sprfmo2026benchmark]. It is the benchmark decision record that\ndefined the assessment foundation and identified which uncertainties should be\nfixed, retained as OM axes, or examined diagnostically.\n\nFollowing SCW16 and before the SCW17 workshop, the working group prepared\n[SCW17/Paper-01: Model developments](https://sprfmo.github.io/scw17/SCW17-Paper-01-ModelDevelopments.html)\n[@sprfmo2026modeldevelopments]. That paper explicitly bridged the SCW16\nbaseline (`0.00`) and proposed final benchmark configuration (`0.14`) to the\npost-benchmark `0.15` and `0.16` developments. It documented the revised\ntreatment of the Peruvian artisanal and industrial CPUE series, the change to\nthe two-stock productivity-regime specification in `0.16`, comparisons with\nthe benchmark anchor models, and diagnostics for the configurations presented\nfor MSE conditioning. SCW17 subsequently used `h1_0.16` as the primary basis\nfor CMP testing, retained the matching two-stock configuration for structural\nrobustness, and retained the SC13-era `0.00`/`1.14` configuration as an\nassessment/configuration robustness case. Thus, the current OM set should be\nread as the product of the SCW16 benchmark followed by a documented\npost-benchmark model-development step, rather than as a set first defined at\nSCW17.\n\nThe current grid centers on the one-stock benchmark model `h1_0.16` with\nsteepness 0.65. Robustness OMs test major structural and parametric\nuncertainties rather than assigning probability to one forecast\n(@tbl-om-set).\n\n| OM label | Main contrast | Analytical role | Proposed decision treatment |\n|:---|:---|:---|:---|\n| om11 | One stock, model 0.16, steepness 0.65 | Reference OM for current tuning | Primary comparison; not assigned a numerical plausibility weight |\n| om11_1 | Alternative selectivity | Younger/smaller fish exposed to greater fishing pressure | Structural sensitivity that may affect reference-point interpretation |\n| om11_2 | One-year recruitment crash | Acute recruitment stress | Stress test; concern should be reported rather than silently pooled |\n| om11_3 | Seven-year cyclic recruitment reduction | Prolonged recruitment stress | Stress test; concern should be reported rather than silently pooled |\n| om12 | One stock, steepness 0.8 | Productivity robustness | Parameter sensitivity |\n| om13 | One stock, SC13-era/model 1.14 configuration | Assessment/configuration robustness | Legacy-configuration sensitivity |\n| om21 | Two stocks, no movement | Stock-structure and catch-distribution robustness | Structural sensitivity requiring component-level results |\n| om21_1 | Two stocks with movement | Spatial redistribution and indicator-conflict robustness | Difficult structural case requiring an explicit SC14 judgment |\n| om22 | Two stocks, steepness 0.8 | Two-stock productivity robustness | Structural and parameter sensitivity requiring component-level results |\n| om23 | Two stocks, model 1.14 configuration | Two-stock assessment/configuration robustness | Difficult legacy-configuration case requiring an explicit SC14 judgment |\n\n: Reference and robustness operating-model set. {#tbl-om-set}\n\nThe OM set (reference and robustness) is not a declaration that all states are\nequally plausible. No numerical plausibility weights have been agreed. The\nproposed treatments above keep the reference comparison, structural\nsensitivities, and deliberate stress tests distinct while bringing difficult\nresults forward. SC14 should decide whether any case is exclusionary, a source\nof concern, or informative but non-decisive; any later OM weighting must be\nexplicit and documented.\n\n### Recruitment, observation, and implementation uncertainty\n\nRecruitment variability strongly influences stock trajectories and dynamic\nreference points. The core simulations therefore retain recruitment\nuncertainty, while discrete crash and cyclical-reduction cases act as stress\ntests. SCW17 treated ENSO and climate effects as robustness questions at this\nstage rather than embedding a single climate forecast in the core OM.\n\n### Dynamic reference points\n\nEnvironmental recruitment variability can make static reference points\nmisleading. In [paragraph 58 of the SCW17 workshop\nreport](https://sprfmo.github.io/scw17/SCW17-MSE-Workshop-report.html#reference-points-and-kobe-plot-summaries),\nthe Working Group strongly recommended calculating the ratio\n$B_{\\mathrm{MSY}}/B_0$ within each MCMC draw, multiplying it by the\ncorresponding dynamic $B_0$, and evaluating spawning biomass relative to that\ndynamic $B_{\\mathrm{MSY}}$. The current tuning objective uses a dynamic\nKobe-green measure that combines biomass and fishing-pressure status.\n\nReference-point choices remain consequential. In particular, alternative\nselectivity can change $F_{\\mathrm{MSY}}$ and therefore\n$F/F_{\\mathrm{MSY}}$ even when biomass and catch trajectories are similar.\nInterpretation should separate changes caused by reference-point definitions\nfrom changes in underlying CMP behavior.\n\n### Generating OM data indices\n\nEach CMP receives simulated abundance indices rather than true stock status.\nProjected index deviations include autocorrelation and cross-correlation so\nthat the observation model represents the estimated historical behavior of\nmultiple surveys and CPUE series. The final values and data coverage used by\nthe reference OM are reported below.\n\nThe combined indicator does not assume that five series provide five\nindependent confirmations of stock change. In each OM iteration, projected\nindex errors are generated jointly from the historical index deviations:\nseries-specific log-scale standard deviations describe uncertainty, lag-1\nparameters preserve temporal autocorrelation, and an iteration-specific\ncorrelation matrix preserves cross-correlation among indices. These\nrelationships matter because common environmental effects, fleet behavior,\nand spatial redistribution of the population can cause several indices to\nrise or fall together.\n\nFor index $i$ in year $t$, the log deviation follows\n$x_{i,t}=\\rho_i x_{i,t-1}+\\epsilon_{i,t}$ and the multiplicative observation\ndeviation is $\\exp(x_{i,t})$. The innovation covariance is constructed from\nthe iteration-specific marginal log-scale standard deviations, lag-1\ncoefficients, and historical cross-correlation matrix. The implementation\nadjusts the innovation correlation for the AR(1) coefficients and applies a\nnearest-positive-definite correction before Cholesky simulation when needed.\nParameters are estimated separately within each posterior iteration from the\navailable historical index deviations through 2025; @tbl-index-error-parameters\nshows their means across iterations.\n\n\n::: {#tbl-index-error-parameters .cell tbl-cap='OM11 index-error parameters and historical coverage used for projection.'}\n::: {.cell-output-display}\n\n\n|Index         | First year| Last year| Years with data| Mean log SD| Mean lag-1 rho|\n|:-------------|----------:|---------:|---------------:|-----------:|--------------:|\n|Chile_AcousN  |       1984|      2025|              25|       0.897|          0.094|\n|Chile_CPUE    |       1998|      2025|              28|       0.171|          0.283|\n|Peru_Artis    |       2002|      2025|              24|       0.302|          0.581|\n|Peru_Ind      |       2002|      2025|              20|       0.348|          0.628|\n|Offshore_CPUE |       2008|      2024|              17|       0.239|         -0.037|\n\n\n:::\n:::\n\n\nThe five series overlap completely only during 2008--2009, 2011--2014, and\n2018--2021. The northern Chile acoustic series has earlier and intermittent\ncoverage, including no 2022 value; the Peruvian industrial series has four\nhistorical gaps; and offshore CPUE ends in 2024. These gaps are retained in\nthe estimation data rather than silently filled. The full mean correlation\nmatrix is downloadable as\n[`index-error-correlations.csv`](../data/index-error-correlations.csv), and the\ncomplete gap list, coverage, and parameter values are in\n[`index-error-parameters.csv`](../data/index-error-parameters.csv).\n\n![OM11 index observation-error correlations. Each cell gives the mean correlation across posterior iterations, with its between-iteration standard deviation in parentheses. Positive values indicate index errors that tend to move together; negative values indicate opposing movements.](../figures/om11-index-observation-error-correlations.png){#fig-om11-index-error-correlations fig-align=\"center\" width=\"88%\" fig-alt=\"Correlation-matrix heat map for the five OM11 abundance indices. Cells show the posterior-iteration mean correlation and standard deviation. The largest positive off-diagonal correlation is 0.54 between the Peru artisanal and Peru industrial indices.\"}\n\nAs shown in @fig-om11-index-error-correlations, the estimated relationships are\nneither uniformly positive nor interchangeable. For example, the Peru\nartisanal and industrial indices have the strongest positive mean\ncross-correlation (0.54), whereas several relationships involving the offshore\nCPUE series are weakly negative. The standard deviations in parentheses show\nthat the observation-error correlation matrix also varies among OM\niterations.\n\nThe resulting closed-loop test therefore exposes the CMP to realistic\ncombinations of agreement, redundancy, and divergence among indicators. The\nnovelty lies in evaluating the simple, transparent equal-weight composite\nunder this estimated multivariate observation process; equal weighting itself\nis not covariance weighting and does not mathematically remove correlation.\nThis approach is consistent with the MSE best-practice principle that\nmanagement procedures should be tested using simulated management data that\nrepresent observation uncertainty rather than receiving true stock status\n[@punt2016mse].\n\nThis model covers stochastic marginal error, persistence, cross-series\ncorrelation, and posterior variation in those estimates. It does **not** by\nitself represent gradual catchability drift, abrupt re-standardization,\nrevised historical data, systematic regional imbalance, or reliability-based\nindex weighting. Tests of those mechanisms, missing-survey rules, and\nregion-balanced or reliability-weighted indicators remain continuing work.\n\n## Candidate management procedures\n\n### Common indicator and annual calculation\n\nThe central CMPs use five observed series: northern Chile acoustic biomass,\nChilean CPUE, Peruvian artisanal and industrial indices, and offshore CPUE.\nEach series is expressed relative to its 2019--2023 mean. The standardized\nvalues are combined with equal weights within each year, after the OMs have\ngenerated the indices using estimated uncertainty, temporal autocorrelation,\nand cross-correlation among series. The CMP then uses a three-year recent\naverage of the combined indicator.\n\nMost data are assumed to arrive with a one-year lag, while offshore CPUE has a\ntwo-year lag. Under the tested timing, a calculation during 2026 for 2027\nadvice would use 2025 values for the acoustic, Chilean CPUE, and Peruvian\nindices, and the 2024 offshore CPUE value. Same-year 2026 observations do not\nenter that tested 2027 calculation unless the timing rule is explicitly\nchanged and re-evaluated, and observations were known to be available in time.\n\n### Naming convention and candidate variants\n\nThe working labels encode the HCR family and the most distinguishing annual\nTAC-change constraint. `HS` means hockey-stick and `PR` means power ramp.\n`+20` identifies the base 20% maximum increase, `-20` identifies the reverse\nasymmetry with a 20% maximum decrease, `sym` identifies symmetric 15% limits,\nand `-30` identifies a 30% maximum decrease. These labels should be used in\nfigures and interpretive prose. The legacy MP identifiers remain in the table\nonly to preserve the link to code, saved outputs, and earlier documents.\nThe complete mapping is given in @tbl-candidate-variants.\n\n### Focal cases and annual-limit sensitivities\n\nAll eight CMPs use the same five-index mean, 2019--2023 reference period,\nthree-year averaging window, 270-kt minimum catch, 0.1 index limit, and\n1,385-kt initial simulated catch. Each variant was refined under the reference\nOM using the same 500 posterior draws after setting its annual constraint.\n\nThe nested development framework in @fig-nested-cmp-development shows how the\nfocused comparison was constructed: first select the HCR shape, then its target\ncatch, and finally tune the trigger controlling the indicator-to-catch\nresponse, while retaining the common minimum catch and index limit. The figure\nrecords the earlier 100-draw trigger controls used during development; the\nsubsequent common 500-draw refinement used for current results is reported in\n@tbl-candidate-variants.\n\n![Nested development of the focused CMP set from HCR family through target catch and tuned response to the resulting HS and PR cases. Trigger values in this development diagram are the earlier 100-draw controls; the current 500-draw refined controls are given in @tbl-candidate-variants.](../figures/candidates/nested_cmp_development.png){#fig-nested-cmp-development fig-align=\"center\" width=\"100%\" fig-alt=\"Flow diagram showing how the CMP comparison narrows from two harvest-control-rule families to hockey-stick and power-ramp targets, common minimum and limit settings, and the eight annual-change variants used in the 500-draw comparison.\"}\n\nThe matched example in @fig-hcr-shape-comparison isolates the effect of HCR\nshape by assigning both rules the same minimum, target, limit, and trigger. The\nhockey-stick increases catch advice linearly and then remains at its target.\nThe power ramp is more conservative below the trigger but continues above the\ntarget when the index exceeds the trigger. Its second panel illustrates the\nharvest-rate pattern that would follow **if** vulnerable biomass were directly\nproportional to the index. For both HCR forms, the implied harvest rate rises\nat low stock sizes because catch advice is not allowed to fall below the\n270-kt minimum; that fixed catch floor becomes an increasing proportion of the\nvulnerable biomass as stock size declines. The panel is explanatory rather\nthan an estimated performance result or an additional rule used by the CMPs.\n\n![Matched illustration of hockey-stick and power-ramp responses to the same relative index. Both examples use a 270-kt minimum catch, 2,000-kt target, 0.1 index limit, and trigger of 2 solely to isolate rule shape; the focal HS and PR CMPs retain their own targets and refined triggers listed in @tbl-candidate-variants. The implied-harvest-rate panel assumes vulnerable biomass is proportional to the index and is conceptual rather than a simulated performance result.](../figures/candidates/hcr_shape_matched_comparison.png){#fig-hcr-shape-comparison fig-align=\"center\" width=\"100%\" fig-alt=\"Two matched panels compare hockey-stick and power-ramp catch advice against the relative index, plus their conceptual implied harvest rates. The hockey-stick becomes flat at its target, while the power ramp continues increasing above its trigger.\"}\n\n```{=latex}\n\\begingroup\\small\n```\n\n\n::: {#tbl-candidate-variants .cell tbl-cap='Naming convention, legacy identifiers, and definitions of the eight candidate variants.'}\n::: {.cell-output-display}\n\n\n|Working label |Legacy ID |HCR family   | Target or breakpoint (kt)| Tuned trigger| Annual decrease/increase limits|\n|:-------------|:---------|:------------|-------------------------:|-------------:|-------------------------------:|\n|HS+20         |MP29      |Hockey-stick |                     2,000|         2.125|                     -15% / +20%|\n|HS-20         |MP43      |Hockey-stick |                     2,000|        1.9375|                     -20% / +15%|\n|HSsym         |MP45      |Hockey-stick |                     2,000|        2.0625|                     -15% / +15%|\n|HS-30         |MP47      |Hockey-stick |                     2,000|             2|                     -30% / +20%|\n|PR+20         |MP32      |Power ramp   |                     1,500|      1.640625|                     -15% / +20%|\n|PR-20         |MP44      |Power ramp   |                     1,500|     1.6015625|                     -20% / +15%|\n|PRsym         |MP46      |Power ramp   |                     1,500|         1.625|                     -15% / +15%|\n|PR-30         |MP48      |Power ramp   |                     1,500|      1.578125|                     -30% / +20%|\n\n\n:::\n:::\n\n\n```{=latex}\n\\endgroup\n```\n\nThe 500-draw refinement began from the earlier 100-draw tuned controls rather\nthan restarting from a broad search. It then evaluated nearby trigger values\nunder one saved OM and common random-number configuration. The resulting\ndynamic Kobe-green probabilities for HS+20, HS-20, HSsym, HS-30, PR+20,\nPR-20, PRsym, and PR-30 are 61.0%, 59.2%, 60.4%, 60.4%, 60.3%, 59.8%, 59.5%,\nand 60.6%, respectively.\n\nA completed local trigger check tested one grid step below and above every\nselected control using the same saved 500 draws. The steps were 0.0625 for\nthe hockey-stick rules and 0.03125 for the power-ramp rules, matching the final\nbisection resolution for each family. All eight checks behaved as expected:\na higher trigger produced a higher long-term Kobe-green probability and a\nlower trigger produced a lower probability. Across the eight CMPs, one lower\nstep changed the probability by -1.36 to -1.74 percentage points and one upper\nstep changed it by +1.10 to +1.84 points. In plain language, this is a local\ntolerance profile: it checks how much the tuning result changes after a small\nmove on either side of the chosen trigger, rather than assuming the selected\nnumber is uniquely precise. The full values are saved in the\n[trigger-tolerance summary](../data/candidates/trigger_tolerance_summary_500.csv).\n\nThe hockey-stick increases advice linearly between the limit and trigger and\nthen reaches a plateau. The power ramp reduces catch more quickly when the\nindicator is below its trigger and can continue to increase above its stated\nbreakpoint according to the implemented rule. These structural differences,\nnot the labels alone, create the main responsiveness-versus-stability contrast.\n\nThe completed 500-draw refinement is a higher-replication evaluation of the\nsame conceptual CMPs, not a new set of procedures. Its controls and performance\noutputs are now the common basis for the candidate summaries in this report.\n\n### Annual TAC-change variants\n\nThe base CMPs limit annual advice to a 15% decrease and a 20% increase. The\ntask team identified a limited set of alternatives for retuning and\ncomparison, summarized in @tbl-annual-limit-variants.\n\n| HCR family | Base | Reverse asymmetry | Symmetric | Larger decrease |\n|---|---|---|---|---|\n| Hockey-stick | HS+20: -15%/+20% | HS-20: -20%/+15% | HSsym: -15%/+15% | HS-30: -30%/+20% |\n| Power ramp | PR+20: -15%/+20% | PR-20: -20%/+15% | PRsym: -15%/+15% | PR-30: -30%/+20% |\n\n: Annual TAC-change-limit variants by HCR family. {#tbl-annual-limit-variants}\n\nThe variants change both management responsiveness and the tuned trigger.\nThey should therefore be compared as complete, retuned CMPs. The available\n500-draw reference and nine-OM robustness runs support the common\nhigher-replication comparison reported here.\n\nThe following reference-OM plot shows 15 reproducibly selected simulation\niterations for the two hockey-stick asymmetry cases over 2025--2050. Iteration\nIDs are paired exactly across panels: for example, iteration 6 would be shown\nfor both MPs if selected, and every selected ID occurs once in each panel.\nEach iteration has its own line color, and the same iteration uses the same\ncolor in both panels.\nHS-20 is MP43 (`tun43`), with annual limits of -20%/+15%; HS+20 is MP29\n(`tun29`), with limits of -15%/+20%. The vertically stacked panels share a\ncommon catch scale, as shown in @fig-catch-spaghetti.\n\n![Projected catch trajectories for the same 15 simulation iteration IDs under both hockey-stick MPs in the reference operating model. Each iteration retains the same line color in both panels so matching trajectories can be traced through time and across MPs.](../figures/candidates/catch_spaghetti_hs_reference.png){#fig-catch-spaghetti fig-align=\"center\" width=\"95%\" fig-alt=\"Two time-series panels show projected 2025 to 2050 catch for the same 15 simulation draws under HS-20 and HS+20. Matching draws follow similar broad stock-driven patterns, while the annual limits alter the size and timing of changes.\"}\n\n### Choice of indices\n\nA CPUE/fishery-index-only comparison was more responsive but produced slightly\nlower short-term catch and higher short-term catch variability. The task team\nretained all five indices for the current focal comparison. The northern\nChile acoustic survey is the only fishery-independent abundance index in the\nset and provides information that fishery-dependent series cannot fully\nreplace. Conversely, equal weighting across regions can become problematic if\nnorthern and southern components diverge. These two findings support retaining\nthe acoustic series while also monitoring regional index groups separately.\n\n## Performance evaluation and the draft scorecard\n\n### Performance framework\n\nSCW17 agreed that CMPs should be evaluated across safety, yield, stability,\nand feasibility rather than by the tuning target alone. Tuning several CMPs to\nthe same Kobe-green objective makes that objective a control for comparison,\nnot a sufficient ranking statistic. The full performance framework can include:\n\n- probabilities of dynamic Kobe-green, low biomass, overfishing, and stock\n  collapse;\n- spawning biomass, vulnerable biomass, and fishing pressure relative to\n  reference points;\n- short-, medium-, and long-term catch;\n- interannual catch change and the frequency with which TAC-change limits bind;\n- low-catch, minimum-catch, and fishery-shutdown-like outcomes;\n- effort or catchability feasibility diagnostics; and\n- robustness measures across individual OMs and stress tests.\n\nA short headline table can aid Scientific Committee review, but the complete\nmetric set and underlying distributions should remain available in the\ntechnical annex and interactive outputs.\n\nThe augmented candidate exports include vulnerable biomass relative to its\n2025 level and relative to equilibrium vulnerable biomass at the fishing\nmortality that produces MSY. Vulnerable biomass was selected to provide a\nperformance measure related to the fish available to the fishing fleet under\nthe modeled selectivity, complementing spawning-biomass measures of biological\nstock condition. Reference-OM results are shown in @fig-vb-reference and the\ncorresponding robustness results in @fig-vb-robustness.\n\n![Vulnerable-biomass performance for the reference operating model.](../figures/candidates/vb_reference.png){#fig-vb-reference fig-align=\"center\" width=\"90%\" fig-alt=\"Point and interval plots compare vulnerable biomass relative to 2025 and relative to the vulnerable-biomass level associated with MSY for eight CMPs in the reference operating model, in near- and long-term periods.\"}\n\n![Vulnerable-biomass performance across the five single-stock CJM robustness operating models. The four two-stock operating models are omitted from this pooled figure because their Northern and Southern components require stock-specific interpretation and are examined separately in the robustness results.](../figures/candidates/vb_robustness.png){#fig-vb-robustness fig-align=\"center\" width=\"90%\" fig-alt=\"Faceted point and interval plots compare two vulnerable-biomass ratios for eight CMPs across five single-stock alternative operating models and near- and long-term periods. Differences among operating models are larger than many differences among CMPs.\"}\n\n### Performance metrics by CMPs\n\nThe quilt in @fig-candidate-quilt is an unweighted comparison of the eight\nannual-change variants listed in @tbl-candidate-variants under the reference\nOM. Annual values were averaged over 2041--2050 within each simulation\niteration; cell labels are medians of those iteration means. Color is\nnormalized independently within each metric across the eight variants.\n\nPurple means lower relative preference and light lavender means higher relative\npreference (0 is darkest; 1 is lightest). Higher\n$SB/SB_{\\mathrm{MSY}}$, catch, $VB/VB_{2025}$, and\n$VB/VB_{\\mathrm{MSY}}$ are treated as better; lower\n$F/F_{\\mathrm{MSY}}$, IACC, dynamic Kobe-red probability,\nprobability of catch below 270 kt, and mean annual catch reduction are treated\nas better. Lower\n$F/F_{\\mathrm{MSY}}$ represents lower fishing pressure, while catch is shown\nseparately. The within-column color scale is not an absolute biological or\nmanagement threshold and must not be interpreted as a rank or recommendation.\n\nThe Kobe-red probability uses the same dynamic biomass denominator as the\ntuning objective: the equilibrium $SB_{\\mathrm{MSY}}/SB_0$ fraction is applied\nto projected unfished spawning biomass in each year and iteration. The\nlow-catch probability is the proportion of all valid iteration-year catch\noutcomes below 270 kt during 2041--2050. Thus, if 10% of iterations are below\n270 kt for five of the ten years and all are above it for the other five, the\nreported probability is 5%. Mean catch reduction averages positive annual\npercentage reductions during 2026--2050. Kobe-red probability and mean catch\nreduction are included in the illustrative composite score below. The\nlow-catch diagnostic remains displayed but is not included in the worked\ncomposite until its management weight is reviewed. Kobe-green probability is omitted from\nthe quilt because it is already the common tuning objective and provides\nlittle independent contrast among the closely tuned CMPs.\n\n![Reference-OM candidate performance metrics for the eight naming-convention variants. Cell labels are median iteration summaries except Kobe-red probability and probability of catch below 270 kt, which pool all valid 2041--2050 iteration-years. Purple indicates lower relative preference and light lavender indicates higher relative preference within each metric (0 is darkest; 1 is lightest).](../figures/candidates/candidate_quilt_reference.png){#fig-candidate-quilt fig-align=\"center\" width=\"100%\" fig-alt=\"Quilt table comparing eight CMPs across nine stock, catch, variability, and risk measures for 2041 to 2050. Each cell contains the numerical result, so color is not the only way to compare cases; no CMP is best on every measure.\"}\n\nThe underlying values, preferred directions, metric ranges, and normalized\nscores are saved in\n[`candidate_quilt_reference_summary.csv`](../data/candidates/candidate_quilt_reference_summary.csv).\nAn editable scorecard input layer is saved in\n[`candidate_scorecard_input_reference.csv`](../data/candidates/candidate_scorecard_input_reference.csv).\nIt converts quilt relative preference to a 0--100 benefit score, records the preferred\ndirection and raw value, and supplies editable `include` and `weight` columns.\nThe default weight is one for every metric, but no weighted total is calculated\nin this export. Changing weights or aggregating scores remains an explicit\nuser decision under the method below.\n\n### Extensible weighted-scorecard method\n\nThe scorecard should be read as three connected layers, with no layer replacing\nthe one before it:\n\n1. **Raw performance and uncertainty.** Report the performance statistic in\n   its original units together with its simulated distribution or an\n   appropriate interval. This is the primary results layer and includes, for\n   example, catch in kt, biomass and fishing-pressure ratios, probabilities,\n   and IACC. The boxplots and uncertainty bars elsewhere in this report provide\n   examples. Point estimates alone are insufficient where CMP distributions\n   overlap.\n2. **Threshold- or target-based absolute performance.** Where the Scientific\n   Committee or Commission has agreed a biologically or operationally\n   meaningful target and limiting boundary, performance can be expressed\n   relative to those fixed reference values. Potential applications include\n   dynamic Kobe probabilities, biomass thresholds, low-catch risk, and an\n   agreed tolerance for interannual catch variability. The target, limiting\n   boundary, direction, time window, and treatment of uncertainty must be\n   specified before calculating this layer; they must not be inferred from the\n   candidate results.\n3. **Range-normalized relative preference.** For metrics without agreed\n   absolute targets, the quilt can scale each CMP between the least and most\n   preferred observed values. This supports comparison across unlike units but\n   describes position within the current candidate set, not absolute\n   performance or acceptability.\n\nFor an absolute higher-is-better metric with agreed limiting boundary $L_m$\nand target $T_m>L_m$, one possible transparent score is\n\n$$\na_{jm}=\\min\\!\\left(1,\\max\\!\\left(0,\n\\frac{x_{jm}-L_m}{T_m-L_m}\\right)\\right).\n$$\n\nFor a lower-is-better metric with $T_m<L_m$, the numerator and denominator are\nreversed: $a_{jm}=\\min(1,\\max(0,(L_m-x_{jm})/(L_m-T_m)))$. These forms are\nillustrative; an agreed probability, risk tolerance, or other metric-specific\nfunction may be preferable. Unlike min--max normalization, fixed $L_m$ and\n$T_m$ values permit comparison across candidate sets and report versions.\n\nThe current worked scorecard implements **Layer 3**, using the performance\nquilt in @fig-candidate-quilt as a reproducible relative trade-off calculation\nfor the eight candidate variants under the reference OM. It does not yet\ncalculate Layer 2 absolute scores because the necessary metric-specific targets\nand limiting boundaries have not been agreed. Let\n$x_{jm}$ be the value for CMP $j$ and metric $m$, and let $x_m^{\\min}$ and\n$x_m^{\\max}$ be the minimum and maximum across the included CMPs. The\ndirectionally normalized preference score $p_{jm}$ is\n\n$$\np_{jm} =\n\\begin{cases}\n\\dfrac{x_{jm}-x_m^{\\min}}{x_m^{\\max}-x_m^{\\min}},\n& \\text{if higher values are preferred},\\\\[6pt]\n\\dfrac{x_m^{\\max}-x_{jm}}{x_m^{\\max}-x_m^{\\min}},\n& \\text{if lower values are preferred}.\n\\end{cases}\n$$\n\nThus $p_{jm}=0$ is the least preferred observed value and $p_{jm}=1$ is the\nmost preferred observed value for that metric and comparison set. It is a\nrelative-preference score, not an acceptability score. If all CMPs\nhave the same value for a metric, they are tied at $p_{jm}=1$. With inclusion\nindicator $I_m$ and non-negative weight $w_m$, the aggregate score is\n\n$$\nS_j =\n100\\,\n\\frac{\\sum_m I_m w_m p_{jm}}\n     {\\sum_m I_m w_m}.\n$$\n\nThe companion Slick Spider (radar) view applies a higher-is-better orientation\nto its displayed metrics and repeats the 0--1\nnormalization within each selected OM. It is useful for seeing how the shape of\nCMP trade-offs changes among OMs, but radar shapes from different OMs do not\nshow absolute changes in performance because each OM is scaled separately.\n\nThe contribution of metric $m$ to the total is\n$C_{jm}=100 I_m w_m p_{jm}/\\sum_m I_m w_m$, so\n$S_j=\\sum_m C_{jm}$. The\n[R implementation](https://github.com/sprfmo/jmMSE26/blob/main/R/build_candidate_scorecard.R)\nreads the editable @fig-candidate-quilt input, checks that every CMP has one\nvalue for every included metric, and writes both the totals and metric-level\ncontributions.\n\nThe worked results in @tbl-scorecard-results include eight metrics from\n@fig-candidate-quilt: the established six plus Kobe-red probability and mean\ncatch reduction. The low-catch diagnostic remains a visible input with\n`include = FALSE`. The equal-weight view assigns one-eighth to every included\nmetric. The balanced view assigns half the total weight equally across Catch,\nIACC, and mean catch reduction, and half equally across\n$SB/SB_{\\mathrm{MSY}}$, $F/F_{\\mathrm{MSY}}$, $VB/VB_{2025}$,\n$VB/VB_{\\mathrm{MSY}}$, and Kobe-red probability. All inputs use the reference\nOM and the 2041--2050 summary window used in @fig-candidate-quilt, except mean\ncatch reduction, which summarizes reductions over 2026--2050.\n\nThe spread among CMP point estimates is highly unequal among these metrics.\nAcross the eight CMP medians, the coefficient of variation\n$CV_m=sd_j(x_{jm})/|\\bar{x}_m|$ is 51.2% for IACC, compared with 1.4% for\nCatch, 1.5--2.3% for the four biomass and fishing-pressure ratios, 6.9% for\nKobe-red probability, and 38.3% for mean catch reduction. Within the\nhockey-stick and power-ramp families, IACC CVs are 7.9% and 3.9%, respectively.\nConsequently, ordinary min--max normalization visually expands small absolute\ncontrasts in Catch and stock condition to the same 0--1 range as the much\nlarger contrasts in IACC and mean catch reduction.\n\nTo expose this issue, @tbl-scorecard-results provides a reproducible\n**dispersion-weighted sensitivity**.\nFor this calculation, the weight for metric $m$ is\n\n$$\nw_m^{CV}=\\frac{\\sqrt{CV_m}}{\\sum_k\\sqrt{CV_k}}.\n$$\n\nThe square root moderates the dominance that would result from weighting\ndirectly in proportion to CV. With the current CMP set, the resulting weights\nare 31.4% for IACC, 27.1% for mean catch reduction, 11.5% for Kobe-red\nprobability, 6.6% for $VB/VB_{2025}$, 6.4% for $VB/VB_{\\mathrm{MSY}}$, 6.3%\nfor $F/F_{\\mathrm{MSY}}$, 5.4% for $SB/SB_{\\mathrm{MSY}}$, and 5.3% for\nCatch. These weights answer which metrics most strongly distinguish the\ncurrent CMPs; they do not answer which outcomes management should value most.\nThey must be recalculated if the CMP set changes.\n\n```{=latex}\n\\begingroup\\small\n\\setlength{\\tabcolsep}{9pt}\n```\n\n| CMP | Equal weight | Balanced | Dispersion weighted |\n|:---|---:|---:|---:|\n| HS+20 (MP29) | 70.74 (1) | 70.66 (1) | 80.25 (1) |\n| HSsym (MP45) | 62.81 (2) | 65.51 (2) | 77.98 (2) |\n| PR-20 (MP44) | 48.63 (3) | 46.37 (4) | 29.69 (5) |\n| HS-30 (MP47) | 47.65 (4) | 52.34 (3) | 66.27 (3) |\n| PRsym (MP46) | 43.27 (5) | 41.28 (5) | 29.42 (6) |\n| HS-20 (MP43) | 32.73 (6) | 41.12 (6) | 60.08 (4) |\n| PR-30 (MP48) | 25.14 (7) | 20.11 (8) | 18.03 (8) |\n| PR+20 (MP32) | 23.25 (8) | 21.46 (7) | 18.27 (7) |\n\n: Relative scorecard sensitivity results for the eight performance-metric-quilt CMPs under the reference OM, 2041--2050. The balanced score assigns one-half across Catch, IACC, and mean catch reduction, and one-half across SB/SBMSY, F/FMSY, VB/VB[2025], VB/VB[MSY], and P(Kobe red). The dispersion-weighted sensitivity derives weights from the square root of each metric's across-CMP coefficient of variation. Each cell reports score (rank). {#tbl-scorecard-results}\n\n\n```{=latex}\n\\endgroup\n```\n\nThe machine-readable totals, including the dispersion-weighted sensitivity,\nare in\n[`candidate_scorecard_result_reference.csv`](../data/candidates/candidate_scorecard_result_reference.csv),\nand the individual weighted contributions are in\n[`candidate_scorecard_contributions_reference.csv`](../data/candidates/candidate_scorecard_contributions_reference.csv).\nThese values are a reproducible calculation, but all three orders remain\n**illustrative relative trade-offs rather than management rankings or\nacceptability scores**: none of the weighting schemes is an agreed statement of\nmanagement priorities, and the scores are relative to this candidate set.\n\nThe current worked scorecard based on @fig-candidate-quilt is an **illustrative framework**,\nnot the final scorecard. It contains eight CMPs and nine displayed performance\nmetrics, eight of which are included in the worked composite scores.\nPlease note:\n\n- candidate rows can be added, removed, or replaced as the shortlist evolves;\n- performance columns can be added as further safety, yield, stability,\n  feasibility, and robustness metrics are validated;\n- preferred direction, units, periods, transformation, and weight must be\n  recorded for every metric; and\n- normalization must be recalculated whenever the candidate set changes.\n\nMin--max normalization is relative to the alternatives included. Adding or\nremoving a CMP can therefore change every normalized score even when underlying\nMSE results do not change. This sensitivity is especially important here:\nbecause all eight CMPs have been tuned close to the same 60% dynamic\nKobe-green objective, a narrow absolute range can still be stretched across\nthe full 0--1 relative-preference scale. Absolute distances from agreed targets\nand the uncertainty in the raw outcomes are therefore more informative than\nmin--max ordering when candidates are closely clustered. Weights express\nmanagement priorities and should be\nagreed and recorded rather than presented as scientific constants. A weighted\nscore is a decision aid, not a recommendation, and should always be shown with\nthe Layer 1 underlying values and uncertainty, any defensible Layer 2 absolute\nscores, and sensitivity analyses.\n\n## Main performance and robustness findings\n\n### Biological requirements and the complete OM table\n\nThe approximately 60% dynamic Kobe-green probability used for tuning is a\ncommon comparison control, not a complete safety standard. The earlier\n[COMM8 draft management objective](https://www.sprfmo.int/assets/Meetings/01-COMM/8th-Commission-2020COMM8/reports/annex/Annex-8b-JM-MSE-Management-Objectives.pdf)\nincluded both a probability of being above $B_{\\mathrm{MSY}}$ in 2030 and a\nhigher-probability requirement to remain above $B_{\\mathrm{lim}}$ during\n2025--2040. The later K60 pathway supplied the common long-term Kobe-green\ntuning target. The present results should therefore be used to ask SC14 which\nbiomass-limit, overfishing, time-specific, and component-specific requirements\nmust be met; K60 should not be interpreted as having replaced every earlier\nobjective unless SC14 records that decision.\n\nThe complete machine-readable table contains 112 CMP, OM, and stock-component\nrows and is available as\n[`candidate_biological_decision_table.csv`](../data/candidates/candidate_biological_decision_table.csv).\nIt was generated directly from the checked 500-draw Slick release with\n`R/build_sc14_review_evidence.R`. It reports long-term dynamic Kobe-green\nprobability, three ways of describing the chance that spawning biomass falls\nbelow dynamic $SB_{\\mathrm{MSY}}$, overfishing probability, catch, and IACC.\nThese are candidate diagnostics for discussion, **not agreed limit-reference\ncriteria**. All eight CMPs remain not ready for annual use because their final\noperational specifications are incomplete.\n\n\n::: {#tbl-biological-decision-preview .cell tbl-cap='Decision-table excerpt for the reference OM and the difficult om23 case, 2041--2050.'}\n::: {.cell-output-display}\n\n\n|OM   |Stock    |CMP   |P(green) |P(any SB < 1) |P(F > 1) |  Catch| IACC|\n|:----|:--------|:-----|:--------|:-------------|:--------|------:|----:|\n|om11 |CJM      |HS+20 |61.0%    |45.2%         |37.0%    | 1570.8|  5.5|\n|om11 |CJM      |HS-20 |59.2%    |47.2%         |38.7%    | 1552.0|  5.6|\n|om11 |CJM      |HSsym |60.4%    |45.4%         |37.4%    | 1557.9|  5.4|\n|om11 |CJM      |HS-30 |60.4%    |46.4%         |37.5%    | 1568.7|  6.0|\n|om11 |CJM      |PR+20 |60.3%    |52.0%         |36.6%    | 1881.5| 10.5|\n|om11 |CJM      |PR-20 |59.8%    |52.2%         |36.4%    | 1923.2| 10.7|\n|om11 |CJM      |PRsym |59.5%    |52.0%         |37.5%    | 1914.4| 10.1|\n|om11 |CJM      |PR-30 |60.6%    |53.2%         |33.8%    | 1865.6| 11.6|\n|om23 |North    |HS+20 |1.1%     |99.0%         |98.9%    |    4.2|  0.6|\n|om23 |North    |HS-20 |0.9%     |99.0%         |99.1%    |    3.2|  0.3|\n|om23 |North    |HSsym |1.0%     |99.0%         |99.0%    |    3.8|  0.5|\n|om23 |North    |HS-30 |1.0%     |99.0%         |99.0%    |    3.5|  0.4|\n|om23 |North    |PR+20 |2.7%     |97.4%         |97.2%    |   10.3|  1.6|\n|om23 |North    |PR-20 |2.9%     |97.0%         |97.1%    |   11.2|  1.8|\n|om23 |North    |PRsym |2.7%     |97.2%         |97.2%    |   10.8|  1.7|\n|om23 |North    |PR-30 |2.7%     |97.2%         |97.3%    |   10.1|  1.6|\n|om23 |Southern |HS+20 |100.0%   |0.0%          |0.0%     | 1284.5|  4.5|\n|om23 |Southern |HS-20 |99.9%    |0.0%          |0.1%     | 1304.2|  4.3|\n|om23 |Southern |HSsym |100.0%   |0.0%          |0.0%     | 1291.0|  4.4|\n|om23 |Southern |HS-30 |99.9%    |0.0%          |0.1%     | 1297.9|  4.4|\n|om23 |Southern |PR+20 |100.0%   |0.0%          |0.0%     | 1234.0|  6.6|\n|om23 |Southern |PR-20 |100.0%   |0.0%          |0.0%     | 1243.4|  6.4|\n|om23 |Southern |PRsym |100.0%   |0.0%          |0.0%     | 1237.0|  6.2|\n|om23 |Southern |PR-30 |100.0%   |0.0%          |0.0%     | 1250.1|  6.8|\n\n\n:::\n:::\n\n\nThe `om23` result requires particular attention. For its northern component,\nlong-term dynamic Kobe-green probability is only 0.9--2.9% across the eight\nCMPs in the current checked release, while the probability of falling below\ndynamic $SB_{\\mathrm{MSY}}$ in at least one year is 97.0--99.0%. This is a\nmodel/configuration sensitivity rather than a forecast, but it must not be\nhidden by pooling OMs or stock components. SC14 should explicitly record\nwhether `om23` is decisive, a concern requiring additional protection or\nanalysis, or too implausible to determine selection.\n\n### Reference comparison\n\nThe illustrative reference-OM scorecard in @tbl-scorecard-results provides the\ncurrent eight-CMP comparison. HS+20 ranks first and HSsym second under all\nthree schemes. Adding Kobe-red probability and mean catch reduction moves\nHS-30 to third under the balanced and dispersion-weighted schemes. The\ndispersion-weighted result then places HS-20 fourth, followed by PR-20, PRsym,\nPR+20, and PR-30. The equal-weight and balanced columns show how several of\nthese middle positions change when metric emphasis changes. The separation\nbetween the two **+20** sensitivity CMPs shows why an analytical role should\nnot be confused with a shared performance ranking.\n\nThis ordering is illustrative and relative to the CMPs, metrics, directions,\n2041--2050 window, and weights included in the scorecard. It does not mean that\none CMP dominates every biological, yield, stability, and responsiveness\nobjective. The underlying values and trade-off figures should therefore remain\nthe basis for interpreting why the order changes with management priorities.\n\n### Reference set trade-offs\n\n**Kobe status.** @fig-kobe-reference-periods provides the direct reference-OM\ncomparison of spawning-biomass status and fishing pressure for the near-term\n(2026--2035) and long-term (2041--2050) periods. Within each posterior\niteration, each ratio is averaged over the stated period; points are the\nmedians of those period means across the 500 iterations. The vertical and\nhorizontal lines at 1 define the conventional Kobe quadrants.\n\n![Near- and long-term Kobe plots for the eight CMPs under the reference operating model. The horizontal axis uses the time-varying dynamic SBMSY denominator used in tuning.](../figures/candidates/kobe_reference_periods.png){#fig-kobe-reference-periods fig-align=\"center\" width=\"95%\" fig-alt=\"Two Kobe panels compare eight candidate management procedures. Spawning biomass relative to dynamic SBMSY is on the horizontal axis and fishing mortality relative to FMSY is on the vertical axis. Panels show 2026 to 2035 and 2041 to 2050.\"}\n\n**Spawning biomass.** The reference-set yield--spawning-biomass comparison uses\nmean catch during 2026--2030 and mean $SB/SB_{\\mathrm{MSY}}$ during\n2036--2040. Points show means among 500 draws, and horizontal and vertical\nbars show the separate 10th--90th percentile ranges for the two measures.\n\n![Reference-OM trade-off for the eight HS and PR configurations.](../figures/sc14-tradeoff-reference.png){#fig-tradeoff-reference fig-alt=\"Near-term catch on the horizontal axis and mean spawning biomass relative to SBMSY on the vertical axis for eight HS and PR candidate configurations under the reference operating model.\"}\n\n@fig-tradeoff-reference shows the reference-OM pattern. The hockey-stick CMPs\ngenerally occupy the higher-catch, lower-biomass part of\nthe plot, while the power-ramp CMPs generally produce lower catch and higher\nbiomass. Responses to the annual-change variants are not monotonic across the\ntwo families because each variant includes a separately tuned trigger as well\nas different change limits. The uncertainty ranges overlap substantially, so\nthe plot should not be read as a deterministic ranking.\n\n![Reference-OM spawning-biomass and interannual-catch-variability trade-off for the eight HS and PR configurations.](../figures/sc14-tradeoff-reference-biomass-iacc.png){#fig-tradeoff-reference-iacc fig-alt=\"Mean spawning biomass relative to SBMSY on the horizontal axis and mean absolute interannual percentage change in catch on the vertical axis for eight HS and PR candidate configurations under the reference operating model.\"}\n\n@fig-tradeoff-reference-iacc provides a complementary reference-OM view of\nbiological status and catch stability. The horizontal axis is the replicate\nmean $SB/SB_{\\mathrm{MSY}}$ during 2036--2040. The vertical axis is mean IACC\nduring the same period, where annual IACC is\n$100|C_t/C_{t-1}-1|$: the plotted period therefore covers the five annual\nchanges from 2035--2036 through 2039--2040. Lower IACC indicates more stable\ncatch. Points are means among 500 draws; horizontal and vertical bars are\nthe separate 10th--90th percentile ranges of the replicate-level period means.\nAs in @fig-tradeoff-reference, overlap is substantial and the marginal bars do\nnot show within-replicate covariance.\n\nThe marked difference in IACC between the four hockey-stick and four\npower-ramp CMPs is not caused by different calculations. For every CMP and\nyear, IACC is calculated identically as\n$100|C_t/C_{t-1}-1|$; an independent recalculation from the saved annual catch\nseries reproduced every stored IACC value exactly. The pattern reflects HCR\nstructure. Hockey-stick advice reaches a constant 2,000-kt target above its\ntrigger, producing many years with essentially no catch change. The power\nramp has no equivalent upper plateau: advice continues to respond to changes\nin the combined indicator above its trigger, so catch can vary even when the\nstock is on the upper branch of the rule. Over 2041--2050, mean IACC is about\n5.4--6.0% for the hockey-stick CMPs and 10.1--11.6% for the power-ramp CMPs.\nThe quilt values are somewhat different because @fig-candidate-quilt reports\nthe median across iteration-specific period means rather than the mean across\nall iteration-years. This structural family contrast is a genuine stability\ntrade-off, but it also means that a highly weighted IACC column can strongly\ninfluence a composite score; the raw IACC distributions and HCR shapes should\ntherefore remain visible alongside any weighted summary.\n\n### Trade-offs under robustness cases\n\n#### Recruitment stress\n\nThe discrete recruitment crash and seven-year cyclic reduction lowered\nlong-term catch and increased catch variability for both central CMPs. PR+20\nresponded more quickly and produced comparatively stronger long-term recovery\nin these tests, while HS+20 retained the relative stability advantages seen in\nthe reference case. These are robustness contrasts, not forecasts that either\nrecruitment path will occur.\n\n#### Alternative selectivity\n\nThe alternative-selectivity OM exposed younger and smaller fish to greater\nfishing pressure. Similar catch levels could then occur with lower spawning\nbiomass and poorer Kobe performance. In the completed results, HS+20 retained\nhigher catch while PR+20 retained higher spawning biomass; this is a trade-off,\ndoes not show that either CMP is uniformly better. Interpretation is also\naffected by the changed $F_{\\mathrm{MSY}}$ reference point.\n\n#### Two-stock hypotheses and catch distribution\n\nIn the two-stock OM without movement, the southern component remained above\nthe agreed benchmark while the northern component did not. An exploratory\nshift of ~3% in simulated catch distribution from north to south brought both\ncomponents to the 60% long-term benchmark.\nThis illustrates sensitivity to spatial exploitation; it is not an allocation\nor catch-distribution recommendation.\n\nIn the movement OM, biomass transferred from the southern to the northern\ncomponent. Because the five indices were combined with equal weights,\nincreasing northern indices could raise the overall indicator while southern\nspawning biomass declined. No tested time-invariant catch distribution\nresolved the long-term benchmark for both components. The test is deliberately\nstressful and does not establish that this movement process is occurring.\nIt does establish a management-relevant warning signal: persistent divergence\nbetween northern and southern indices.\n\n**Spawning biomass.** The saved results also support\nyield--spawning-biomass comparisons across the single-stock and two-stock\nrobustness cases.\n\n![Trade-offs across the five single-stock robustness OMs.](../figures/sc14-tradeoff-single-stock-robustness.png){#fig-tradeoff-single fig-alt=\"Five panels show near-term catch and later spawning biomass relative to SBMSY for eight HS and PR configurations under single-stock robustness operating models.\"}\n\nThe same broad direction is visible across the single-stock robustness cases\n(@fig-tradeoff-single), but the location and separation of configurations\nchanges by OM. Recruitment stress reduces later biomass and changes the\napparent trade-off, while productivity and assessment-configuration\nalternatives move both axes.\n\n![Component-level trade-offs across the four two-stock robustness OMs.](../figures/sc14-tradeoff-two-stock-robustness.png){#fig-tradeoff-two fig-alt=\"A grid of panels shows near-term component catch and later spawning biomass relative to SBMSY for northern and southern components under four two-stock operating models.\"}\n\nFor the two-stock cases (@fig-tradeoff-two), each row is a biological component\nand the horizontal axis is **component catch**, not total catch. The plots\ntherefore diagnose stock-specific consequences and must not be interpreted as\nan allocation comparison. They reinforce the need to keep northern and\nsouthern outcomes separate.\n\nThe spawning-biomass figures in Sections 6.2 and 6.3 use the completed\n500-draw comparison but remain selective summaries for three reasons. First,\nthe x and y uncertainty bars are marginal percentiles and do not show the\nwithin-replicate covariance between\nplotted measures. Second, spawning biomass is shown relative to each draw's\nequilibrium SBMSY rather than in tonnes. This differs from the time-varying\ndynamic SBMSY denominator used for tuning and in @fig-kobe-reference-periods.\nThird, these views cover\nonly selected yield, biological, and catch-stability periods; they do not\ninclude fishing pressure, Kobe-green probability, low-catch risk, feasibility,\nor the other performance measures needed for a decision. The plotted summary\nvalues are saved in `doc/data/sc14-preliminary-tradeoffs.csv` and can be\nregenerated with `R/plot_sc14_tradeoffs.R`.\n\n## Banking, borrowing, and implementation constraints\n\nSCW17 treated banking and borrowing as a sensitivity to apply to the final CMP\nset rather than as feedback within the HCR. Updated 500-iteration results are\nnow available for HS+20 and PR+20 under the reference, low-recruitment, and\ncyclic-recruitment OMs. The tested implementation used a 10% banking or\nborrowing amount when HCR advice changed by at least 15%, subject to the\nCMP-specific healthy-rule condition. In operational terms, a decline of more\nthan 15% made an iteration eligible to **borrow** 10% of the new advice (adding\nit to the current TAC and deducting it subsequently), while an increase of more\nthan 15% made it eligible to **bank** 10% (deducting it from the current TAC and\nmaking it available subsequently).\n\nThe current `msemodules::bank_borrow.is()` implementation also evaluates the\nrecorded HCR branch against the CMP-specific `healthy` threshold. For HS+20\nthis requires rule status 3: the indicator is at or above the hockey-stick\ntrigger and advice is on the constant target branch. For PR+20 it requires rule\nstatus 2: the indicator is at or above the power-ramp trigger and advice is on\nits upper branch. All recorded applications in the updated archive satisfy the\napplicable healthy-branch condition. These B&B runs did **not** retain the\nannual TAC-change limits, so comparison with the standard runs combines the\neffect of banking and borrowing with the effect of removing those limits.\n\nThe long-term results are summarized in @tbl-bb-sb0green. The values with B&B\ncome from the supplied 500-iteration `performance_babs.rds`, whose six run\nidentifiers match the updated `babs.rds` archive. Under the reference OM, mean\nSB0green during 2041--2050 was 0.582 for HS+20 and 0.464 for PR+20. The values\nunder low recruitment were 0.416 and 0.489, respectively, and under cyclic\nrecruitment were 0.409 and 0.455. The without-B&B values added in Iago\nMosqueira's contribution cover the same three OMs, but the comparison is not a\ncontrolled estimate of the incremental B&B effect because the B&B runs removed\nthe annual TAC-change limits.\n\n| OM | CMP | Without B&B | With B&B |\n|:---|:---|---:|---:|\n| Reference OM | HS+20 | 0.603 | 0.582 |\n| Reference OM | PR+20 | 0.607 | 0.464 |\n| Low recruitment | HS+20 | 0.508 | 0.416 |\n| Low recruitment | PR+20 | 0.613 | 0.489 |\n| Cyclic recruitment | HS+20 | 0.407 | 0.409 |\n| Cyclic recruitment | PR+20 | 0.527 | 0.455 |\n\n: Mean SB0green during 2041--2050. Values with B&B use the matched updated\n500-iteration run and performance archives. Values without B&B are the standard\nruns supplied in Iago Mosqueira's contribution. Because annual TAC-change\nlimits were removed from the B&B runs, the columns are not an otherwise-matched\nestimate of the incremental B&B effect. {#tbl-bb-sb0green}\n\nThe spawning-biomass distributions for the six banking-and-borrowing runs in\n@tbl-bb-sb0green are shown in @fig-bb-sbmsy-periods. Each boxplot summarizes\nthe distribution across the 500 iterations after first averaging SB/SBMSY within\neach iteration over the stated period. This is a stock-status ratio, whereas\nSB0green in @tbl-bb-sb0green is the probability of being in the dynamic Kobe\ngreen quadrant; the two summaries are complementary and should not be read as\nthe same performance measure. The dashed line marks SB/SBMSY = 1.\n\n![Spawning biomass relative to SBMSY in the updated 500-iteration banking-and-borrowing runs, for the near-term (2026--2035) and long-term (2041--2050) periods.](../figures/banking-borrowing-sbmsy-periods.png){#fig-bb-sbmsy-periods fig-align=\"center\" width=\"95%\" fig-alt=\"Two boxplot panels show iteration-level mean spawning biomass relative to SBMSY for HS plus 20 and PR plus 20 under the reference, low-recruitment, and cyclic-recruitment operating models. The left panel covers 2026 to 2035 and the right panel covers 2041 to 2050. A dashed horizontal line marks one.\"}\n\nThe updated archive resolves the earlier provenance problem: its six run names\nmatch the performance table, and its `banking.isys` and `borrowing.isys`\ntracking fields contain non-zero recorded applications. @fig-bb-applications\ntherefore counts transactions recorded in the run archive directly, rather\nthan reconstructing eligibility from annual changes in HCR advice. The updated\n500-iteration pattern is consistent in kind with the contractor's earlier\n100-iteration plot, while the exact counts differ because the simulation sample\nis larger and not the same set of draws.\n\n::: {.content-visible when-format=\"pdf\"}\n\\newpage\n:::\n\n![Recorded annual applications of banking and borrowing in the updated 500-iteration runs. Circles denote iterations in which banking was applied and triangles denote iterations in which borrowing was applied.](../figures/banking-borrowing-eligibility.png){#fig-bb-applications fig-align=\"center\" fig-pos=\"H\" width=\"95%\" fig-alt=\"Six-panel plot of recorded banking and borrowing application counts by year. Rows show the reference, low-recruitment, and cyclic-recruitment OMs; columns show HS plus 20 and PR plus 20. Banking is applied more frequently for PR plus 20, while borrowing is relatively uncommon.\"}\n\nIf the intent is to estimate the incremental effect of banking and borrowing,\nthe analysis still requires a matched no-B&B comparison using the same 500 OM\ndraws and the same TAC-change-limit treatment.\n\nEffort feasibility is another implementation constraint. A TAC can be\nmathematically available but difficult to catch when fish distribution or\ncatchability changes. The OM includes an effort cap across all fisheries, set\nat three times the effort level of 2025, to prevent unrealistic projected\neffort. Low realized catch, catch-rate proxies, and the frequency of binding\neffort constraints should be retained as supporting diagnostics.\n\n## Exceptional circumstances and annual monitoring\n\nAn exceptional-circumstances protocol should identify when new information is\ninconsistent with the conditions under which a selected CMP performed\nacceptably. SCW17 considered the ECP software framework as a proof of concept:\nrobustness simulations can identify data patterns associated with poor CMP\nperformance, and detection rules can then be evaluated for false-positive and\nfalse-negative errors.\n\nThe current analysis identifies at least two monitoring priorities:\n\n1. persistent divergence between northern and southern abundance indicators,\n   particularly in relation to the two-stock-with-movement hypothesis; and\n2. whether current survey, catch, and fishery information lies outside OM\n   distributions or is associated with simulated CMP failure states.\n\nPreliminary oral fishery updates reported at the 24 July meeting are not\nvalidated data submissions and do not by themselves establish exceptional\ncircumstances. A protocol should specify the observations, data timing,\ntriggering information, review authority, possible responses, and return-to-rule\nconditions before operational use.\n\n## Summary and conclusions\n\nThis MSE combines the operating-model development and management-procedure\ndesign undertaken before and during SCW17 with the subsequent implementation,\ntuning, robustness testing, and performance evaluation. The candidate\nprocedures apply transparent hockey-stick and power-ramp HCRs to a combined\nindicator constructed from five standardized abundance series. A distinctive\nfeature is that the OMs simulate uncertainty, temporal autocorrelation, and\ncross-correlation among those series, rather than treating multiple indicators\nas independent confirmations of stock change.\n\nThe analysis narrows the broader workshop set to two central rule families and\nreasonable annual TAC-change variants. Candidate performance is evaluated\nagainst a reference OM and a structured robustness set spanning productivity,\nrecruitment stress, selectivity, stock structure, movement, and spatial catch\ndistribution. The results demonstrate trade-offs among biological condition,\ncatch, stability, and responsiveness rather than identifying a single CMP that\ndominates every objective. The performance quilt and worked scorecards provide\ntransparent summaries, but the underlying distributions, metric definitions,\nweights, and robustness results remain necessary for interpretation.\nFor example, MP29 and MP45 (HS+20 and HSsym) receive the two highest\nillustrative composite scores under the reference OM. That result is not a\nclaim that either dominates across the robustness set: their relative\nperformance still depends on the metric, weighting, and robustness scenario\nconsidered.\n\nThe [external experts invited to\nSCW17](https://sprfmo.github.io/scw17/SCW17-MSE-Workshop-report.html#appendix-d.-comments-from-external-experts)\nsupported progressing the MSE. Tom Carruthers considered the framework suitable\nfor testing CMPs, with a defensible reference OM, a comprehensive robustness\nset, relevant performance measures, and empirical CMPs comparable with\nprocedures used in other fisheries. He concluded that the work was sufficiently\nadvanced to support shortlisting defensible CMPs for Scientific Committee\nconsideration and that the improvements still identified were not substantial\nenough to delay adoption of a robust management procedure. He also emphasized\nthat MSE is an ongoing, iterative process in which the framework can be refined\nafter an MP is adopted and applied.\n\nDavid Miller and Rosana Ourens likewise viewed the benchmark assessment as a\nstrong basis for the reference OM, the robustness set as covering important\nuncertainties, and the use of dynamic reference points and simple empirical\nindex-based rules as sensible.\n\n**External-review caveats.** Their comments also stated that CMP design would\nhave benefited from more stakeholder input and that earlier agreement on the\nassessment and reference points would have kept the discussion more focused.\nThose caveats are retained here as reviewer findings.\n\n**Author response.** Commission participants and other stakeholders received\npresentations and opportunities to provide input before and during the MSE\nprocess, including on management preferences and annual TAC-change limits.\nThis history does not remove the reviewers' caveats. It supports continued and\nbetter-documented stakeholder involvement, especially when narrowing the CMP\nset and setting weights or other management preferences.\n\nThe technically relevant priorities identified by the experts include\naccurately representing historical cross-correlation among indices, exploring\nalternative index combinations, and establishing a formal\nexceptional-circumstances framework. Taken together, the external review\nsupports applying the MSE as a living management process, with monitoring,\nstakeholder input, and agreed revisions continuing after initial adoption\nrather than treating the current analysis as a one-time exercise.\n\nThe available work supports asking SC14 to identify a provisional shortlist\nfor final comparative evaluation, accompanied by annual monitoring and a\nformal exceptional-circumstances process. It does not request Commission\nselection or adoption at this stage. Because this synthesis contains\nresult-dependent statements, scores, and conclusions, the\n[interactive scorecard explorer](../application/scorecard.qmd) lets users\ncompare CMPs, select performance metrics, apply alternative weighting schemes,\nand specify weights directly. The application complements rather than replaces\nthe underlying performance distributions and documented management judgments.\n\nThe Scientific Committee is asked to consider the following:\n\n**Noting**\n\n- that the approaches provide valid combinations of the available information\n  for application in the tested HCRs;\n- that the work identifies reasonable annual TAC-change variants informed by\n  polling of Commission members;\n- that the current comparison addresses the K60 tuning pathway but SC14 still\n  needs to state how the earlier COMM8 objectives and component-level risks\n  should be applied;\n- the use of all five indices and the complementary value of the\n  fishery-independent acoustic series;\n- that northern and southern indicators should continue to be tracked\n  separately, as in the past, alongside the combined CMP indicator and\n  monitored through the annual assessment process, including when evaluating\n  whether exceptional circumstances may be occurring;\n- that the updated 500-iteration banking-and-borrowing runs retain explicit\n  transaction tracking and indicate a potentially material effect on MP\n  performance, but require a matched no-B&B comparison before the incremental\n  effect is interpreted for implementation; and\n- that the robustness tests provide plausible scenarios for testing the CMPs.\n\n**Advising**\n\n- the analytical work as satisfying the request from the Commission;\n- identification of a provisional shortlist for final comparative evaluation,\n  without implying selection or adoption;\n- development of a formal exceptional-circumstances protocol, including\n  evaluation of detection performance and pre-agreed responses; and\n- review and documentation of the full performance-metric set and any weighting\n  process, while retaining the underlying outcomes rather than relying on a\n  composite score alone.\n\n## Source, terminology, and interpretation notes\n\nThis synthesis uses \"CMP\" for a procedure still under evaluation and \"MP\" when\nreferring to the identifiers used in the analysis. \"Catch distribution\" is\nused for two-stock sensitivity tests; those tests are not allocation advice.\n\"Dynamic Kobe green\" refers to performance calculated using the dynamic\nreference-point implementation described above.\n\nNumerical values from presentations and meeting materials should be checked\nagainst the named final simulation archive before submission. Where a\npresentation takeaway and the later meeting interpretation differed in tone,\nthis report follows the meeting's more cautious interpretation. The meeting\nreport itself was prepared from meeting notes, transcript material, and an\nautomated meeting summary; preliminary oral information requires confirmation\nagainst formal submissions.\n\n## Sources\n\n::: {#refs}\n:::\n",
    "supporting": [
      "sc14-mse-report_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}