{
  "hash": "929a16c9bf250afc9ea6d5e15ba84689",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Illustrative 2027 TAC calculation\"\n---\n\n```{=html}\n<div class=\"sprfmo-front\">\n  <div class=\"sprfmo-banner\">\n    <h1 class=\"sprfmo-wordmark\">SPRFMO</h1>\n    <div class=\"sprfmo-subtitle\">South Pacific Regional Fisheries Management Organisation</div>\n    <div class=\"sprfmo-rule\"></div>\n    <div class=\"sprfmo-group\">Jack Mackerel Candidate Management Procedures</div>\n  </div>\n</div>\n```\n\n\n<div class=\"paper-title\">How the Candidate Procedures Would Produce 2027 Advice</div>\n\n::: {.status-note}\n**This is a calculation plan, not a 2027 TAC recommendation.** None of the\ncandidate management procedures (CMPs) has been adopted. A numerical\nrecommendation cannot be produced until the complete annual index data, the\nprevious catch-advice value, and the rules for data timing, missing values,\nrounding, and allocation have been confirmed.\n:::\n\nThis page shows how the data available for the 2027 decision would be passed\nthrough each CMP. It also identifies where the approximately 630 kt estimate\nfrom the 2026 northern Chile acoustic survey could, and could not, be used.\n\n## First settle which data year applies\n\nThe current MSE runs use a one-year data delay and a one-year management delay.\nUnder that tested timing:\n\n1. the CMP calculation made in 2026 produces catch advice for 2027;\n2. the most recent observations used are from 2025;\n3. all eight CMPs use 2023–2025 data; and\n4. all eight use the same five-index calculation and three-year averaging\n   window.\n\nThe 2026 northern Chile acoustic estimate therefore **does not enter the 2027\ncalculation as it was tested in the MSE**. It would first enter the following\nannual calculation, for 2028 advice.\n\nUsing observations from 2026 for the 2027 TAC would require a same-year data\nrule. That would change the timing assumed in the tested CMP and should be\nspecified, coded, and checked before it is used. Under such a revised rule, the\nthree-year window would be 2024–2026.\n\n## Data required\n\nAll eight CMPs in the named SC14 release use the same five indices.\n\n| CMPs | Annual series required | Is the northern Chile acoustic survey used? |\n|---|---|---|\n| MP29, MP43, MP45, MP47, MP32, MP44, MP46, MP48 | Northern Chile acoustic survey (`Chile_AcousN`), Chile CPUE, Peru artisanal index, Peru industrial index, and offshore CPUE | Yes, when its data year falls within the approved window |\n\nFor every series, retain the value, unit, survey or fleet coverage, source,\nrevision status, and date received. Values must be comparable with those used\nin the 2019–2023 reference period.\n\n## Turn the observations into the CMP indicator\n\nThe raw indices are on different scales, so they cannot be averaged directly.\nThe current procedure performs the following calculation.\n\n### Express each series relative to its reference-period average\n\nFor index $j$ in year $y$,\n\n$$\nR_{j,y} =\n\\frac{\\text{index }j\\text{ in year }y}\n{\\text{mean of index }j\\text{ over 2019--2023}}.\n$$\n\nA value of 1 means that the observation equals its own 2019–2023 average. A\nvalue of 1.25 means it is 25% above that average.\n\nThe reported acoustic estimate of about 630 kt cannot be entered directly into\nthe harvest rule. If its year is eligible, it must first be checked against the\nsame northern Chile acoustic series and converted to\n\n$$\nR_{\\text{acoustic},2026} =\n\\frac{630\\text{ kt}}\n{\\text{mean northern Chile acoustic biomass over 2019--2023}}.\n$$\n\nThe reference-period mean is not recorded on this site, so this contribution\ncannot yet be calculated here.\n\n### Combine the available series within each year\n\nFor each year, average the relative values for the indices required by the\nCMP. This gives one combined annual index $A_y$.\n\nThe analysis code averages the non-missing series. Before an operational\ncalculation, the Scientific Committee should decide whether a missing required\nseries may be omitted or whether it stops the calculation. A missing value\nshould never be omitted without being reported.\n\n### Average across the recent years\n\nThe indicator supplied to the harvest rule is:\n\n$$\nI = \\text{mean of the combined annual indices over the approved recent years}.\n$$\n\nFor the tested 2027 timing, use 2023–2025 for all eight CMPs. One common\nall-index value of $I$ is supplied to each rule.\n\n## Apply each harvest rule\n\nThe table gives the current settings. Catch quantities use the units of the\n`jmMSE` analysis; those units and the final rounding convention must be\nconfirmed before providing formal advice.\n\n\n::: {#tbl-annual-cmp-settings .cell tbl-cap='Settings for the eight CMPs in the named SC14 release.'}\n::: {.cell-output-display}\n\n\n|CMP          |Information               |Rule         | Minimum| Limit|  Trigger| Target or breakpoint|\n|:------------|:-------------------------|:------------|-------:|-----:|--------:|--------------------:|\n|MP29 (HS+20) |All five indices, 3 years |Hockey-stick |     270|   0.1| 2.125000|                 2000|\n|MP43 (HS-20) |All five indices, 3 years |Hockey-stick |     270|   0.1| 1.937500|                 2000|\n|MP45 (HSsym) |All five indices, 3 years |Hockey-stick |     270|   0.1| 2.062500|                 2000|\n|MP47 (HS-30) |All five indices, 3 years |Hockey-stick |     270|   0.1| 2.000000|                 2000|\n|MP32 (PR+20) |All five indices, 3 years |Power ramp   |     270|   0.1| 1.640625|                 1500|\n|MP44 (PR-20) |All five indices, 3 years |Power ramp   |     270|   0.1| 1.601562|                 1500|\n|MP46 (PRsym) |All five indices, 3 years |Power ramp   |     270|   0.1| 1.625000|                 1500|\n|MP48 (PR-30) |All five indices, 3 years |Power ramp   |     270|   0.1| 1.578125|                 1500|\n\n\n:::\n:::\n\n\nIn the new short-label convention, **HS** means hockeystick and **PR** means\npower ramp. **+20** identifies a 20% maximum annual increase, while **-20**\nidentifies a 20% maximum annual decrease.\n\nFor a hockeystick CMP, the preliminary catch advice is the minimum at or below\nthe limit, rises in a straight line between the limit and trigger, and equals\nthe target at or above the trigger.\n\nFor each power-ramp CMP, let\n\n$$\nx = \\frac{I-\\text{limit}}{\\text{trigger}-\\text{limit}}.\n$$\n\nThe preliminary advice is the minimum when $I$ is at or below the limit. It\nis\n\n$$\n\\text{minimum} + (\\text{target}-\\text{minimum})x^{2.5}\n$$\n\nbetween the limit and trigger, and\n\n$$\n\\text{target}(0.2+0.8x)^{0.6}\n$$\n\nat or above the trigger. Unlike the hockeystick, the power-ramp advice can\ncontinue to rise above its stated target.\n\n## Apply the annual change limit\n\nMP29 and MP32 limit the change from the previous year's catch advice to a 15%\ndecrease or a 20% increase. If $C^*$ is the preliminary advice and $C_{2026}$\nis the agreed previous advice value, the 2027 value before rounding is\n\n$$\nC_{2027} =\n\\max\\left(0.85C_{2026},\n\\min\\left(C^*,1.20C_{2026}\\right)\\right).\n$$\n\nMP43 and MP44 instead allow a 20% decrease and a 15% increase:\n\n$$\nC_{2027} =\n\\max\\left(0.80C_{2026},\n\\min\\left(C^*,1.15C_{2026}\\right)\\right).\n$$\n\nMP45 and MP46 use symmetric 15% limits. MP47 and MP48 allow a 30% decrease and\na 20% increase. The exact multipliers are read from the CMP registry in the\nworked calculation below. Under reference OM11, the realized mean\nprobabilities of being in the dynamic Kobe green zone over 2041–2050 were\n0.6098, 0.5918, 0.6042, 0.6038, 0.6026, 0.5984, 0.5954, and 0.6056 for MP29,\nMP43, MP45, MP47, MP32, MP44, MP46, and MP48, respectively.\n\nThe value 1385 appears as the initial value in the simulation controls. It\nshould not automatically be treated as $C_{2026}$. The operational\nspecification must say whether the annual limit is based on the previous TAC,\nthe previous CMP recommendation, or another approved quantity.\n\n## Worked retrospective: 2025 advice using data through 2024\n\nFor this retrospective, the advice year is labelled as the year immediately\nafter the last data year: 2024 observations produce illustrative 2025 advice.\nThis simply backs the calendar labels up one year while retaining the candidate\nindex calculations, harvest rules, and initial comparison value of 1385.\n\nThis remains an illustration rather than advice adopted by SPRFMO. The result\nis a total catch quantity in the analysis units, before an approved rounding\nrule or allocation among fisheries.\n\n\n\n### Historical inputs\n\nThe table contains the observations from the updated assessment data associated\nwith `input/0.15.dat`. The two Peruvian series are retained separately as\n`Peru_Artis` and `Peru_Ind`. Each reference mean is calculated over the\navailable observations in 2019–2023. The northern acoustic series has no 2022\nvalue.\n\n\n::: {#tbl-retrospective-inputs .cell tbl-cap='Historical observations used for the retrospective calculation. A dash means that no value is stored.'}\n::: {.cell-output-display}\n\n\n|   |Series        | 2019–2023 mean|     2022|     2023|     2024|     2025|\n|:--|:-------------|--------------:|--------:|--------:|--------:|--------:|\n|1  |Chile_AcousN  |       1896.963|        —| 2502.157| 2788.465| 3058.843|\n|2  |Chile_CPUE    |         96.249|   90.157|   98.162|   82.478|   97.287|\n|4  |Peru_Artis    |          0.507|    0.571|    0.617|    0.672|    0.495|\n|5  |Peru_Ind      |          0.686|    0.736|    0.683|    0.656|    0.630|\n|3  |Offshore_CPUE |        937.613| 1339.693| 1169.402|  428.054|        —|\n\n\n:::\n:::\n\n\n### Indicators for the 2025 calculation\n\nThe all-index annual values are 1.141 for 2022, 1.159 for 2023, and\n1.013 for 2024. Their three-year mean is 1.104. This same indicator is supplied\nto each of the eight rules.\n\n\n::: {#tbl-retrospective-indicators .cell tbl-cap='Relative-index values supplied to the candidate harvest rules for the retrospective 2025 calculation.'}\n::: {.cell-output-display}\n\n\n|Used by             |Index set        |Years averaged | Indicator|\n|:-------------------|:----------------|:--------------|---------:|\n|All eight SC14 CMPs |All five indices |2022–2024      |     1.104|\n\n\n:::\n:::\n\n\n### Turn the indicator into preliminary advice\n\nThe indicator is a relative measure, not a catch quantity. A value of 1 means\nthat the recent indices are, on average, equal to their 2019–2023 reference\nlevels. A value above 1 means they are higher; a value below 1 means they are\nlower.\n\nEach candidate then puts its indicator into its own harvest-control rule. The\nrule converts the relative indicator into a catch quantity. Because the\ncandidates have different limits, triggers, targets, and rule shapes, the same\nindicator can produce different preliminary advice.\n\nWe write this preliminary catch advice as $C^*$. Here, $C$ means catch advice\nand the star means **provisional**: it is the harvest-control-rule result before\nthe annual change limit is applied. The star is not another calculation.\n\nThe table shows the substitution explicitly. Values displayed in the\ncalculation are rounded to three decimal places; the code uses the unrounded\nvalues.\n\n\n::: {#tbl-indicator-to-advice .cell tbl-cap='How each candidate converts its indicator into preliminary catch advice (C*).'}\n::: {.cell-output-display}\n\n\n|CMP  | Indicator|Rule        |Substitute the indicator in the rule                                                            | C* before annual limit|\n|:----|---------:|:-----------|:-----------------------------------------------------------------------------------------------|----------------------:|\n|MP29 |     1.104|Hockeystick |270.000 + (1.104 − 0.100) × (2000.000 − 270.000) ÷ (2.125 − 0.100)                              |               1128.100|\n|MP43 |     1.104|Hockeystick |270.000 + (1.104 − 0.100) × (2000.000 − 270.000) ÷ (1.938 − 0.100)                              |               1215.661|\n|MP45 |     1.104|Hockeystick |270.000 + (1.104 − 0.100) × (2000.000 − 270.000) ÷ (2.062 − 0.100)                              |               1155.428|\n|MP47 |     1.104|Hockeystick |270.000 + (1.104 − 0.100) × (2000.000 − 270.000) ÷ (2.000 − 0.100)                              |               1184.554|\n|MP32 |     1.104|Power ramp  |x = (1.104 − 0.100) ÷ (1.641 − 0.100) = 0.652; 270.000 + (1500.000 − 270.000) × x raised to 2.5 |                692.139|\n|MP44 |     1.104|Power ramp  |x = (1.104 − 0.100) ÷ (1.602 − 0.100) = 0.669; 270.000 + (1500.000 − 270.000) × x raised to 2.5 |                720.131|\n|MP46 |     1.104|Power ramp  |x = (1.104 − 0.100) ÷ (1.625 − 0.100) = 0.659; 270.000 + (1500.000 − 270.000) × x raised to 2.5 |                703.035|\n|MP48 |     1.104|Power ramp  |x = (1.104 − 0.100) ÷ (1.578 − 0.100) = 0.680; 270.000 + (1500.000 − 270.000) × x raised to 2.5 |                738.187|\n\n\n:::\n:::\n\n\nFor example, MP29 uses the hockeystick rule:\n\n$$\nC^* =\n270 +\n\\frac{(1.104-0.100)(2000-270)}\n     {(2.125-0.100)}\n= 1128.10.\n$$\n\nThe value 1128.10 is therefore MP29's harvest-rule result. It is not yet the\nfinal value because the annual change limit must still be applied.\n\n### Apply the annual change limit\n\nWith 1385 as the initial comparison value, each CMP applies the decrease and\nincrease multipliers recorded in the registry. The table reports the range\nthat affects each result rather than applying one common limit to all CMPs.\n\n\n::: {#tbl-retrospective-advice .cell tbl-cap='Illustrative 2025 total catch advice using observations through 2024 and an initial comparison value of 1385.'}\n::: {.cell-output-display}\n\n\n|CMP  |Index years | Indicator| C* before annual limit|Adjustment         | Result after annual limit|\n|:----|:-----------|---------:|----------------------:|:------------------|-------------------------:|\n|MP29 |2022–2024   |     1.104|               1128.100|15% decrease floor |                  1177.250|\n|MP43 |2022–2024   |     1.104|               1215.661|None               |                  1215.661|\n|MP45 |2022–2024   |     1.104|               1155.428|15% decrease floor |                  1177.250|\n|MP47 |2022–2024   |     1.104|               1184.554|None               |                  1184.554|\n|MP32 |2022–2024   |     1.104|                692.139|15% decrease floor |                  1177.250|\n|MP44 |2022–2024   |     1.104|                720.131|20% decrease floor |                  1108.000|\n|MP46 |2022–2024   |     1.104|                703.035|15% decrease floor |                  1177.250|\n|MP48 |2022–2024   |     1.104|                738.187|30% decrease floor |                   969.500|\n\n\n:::\n:::\n\n\nThese values should not be interpreted as eight equally supported\nrecommendations: MP43 and MP44 are the focal cases, MP29 and MP32 are\nsensitivity cases, and MP45--MP48 are comparison cases. The table checks that\nevery rule can be reproduced from one shared set of observations and the\nsettings in the named registry.\n\n## Why this example stops with 2024 observations\n\nThe updated data contain both Peruvian series through 2025, but the 2025\noffshore CPUE is absent. Rather than silently omit that series or invent a\nreplacement, the worked calculation backs off one year and uses the complete\nset available through 2024. Once the missing-data rule and 2025 offshore CPUE\nstatus are settled, the same calculation can be advanced one year to produce\nan illustrative 2026 result.\n\n## Complete and record the recommendation\n\nFor each CMP, save:\n\n1. the original data files and their units;\n2. the 2019–2023 average for each index;\n3. every annual relative index $R_{j,y}$;\n4. the combined annual indices $A_y$;\n5. the recent-year indicator $I$;\n6. the preliminary harvest-rule result $C^*$;\n7. the previous-advice value and annual-change adjustment;\n8. the unrounded and rounded total recommendation;\n9. any allocation calculation; and\n10. all missing-data, revision, or exceptional-circumstances warnings.\n\nThe current simulations divide the total catch among fisheries using average\ncatch shares over the previous five years. The release check records this\nimplemented method consistently. It is not treated here as a further\nanalytical comparison; responses to review comments about allocation are\nhandled separately.\n\n## What can be concluded from the currently reported value\n\nThe approximately 630 kt acoustic estimate alone is not sufficient to\ncalculate a TAC:\n\n- it is outside the tested data window for a 2027 recommendation;\n- it must be expressed relative to the 2019–2023 average for the same survey;\n- the other four required indices are also needed.\n\nOnce the complete annual data table and the agreed previous-advice value are\navailable, the calculations above can be run side by side to show the\nrecommendation produced by every candidate.\n\n## Implementation basis\n\nThis calculation plan is part of `SC14-MSE-2026-RC1`. It reads the eight\ncurrent settings directly from the\n[CMP registry](../data/cmp-registry.csv). The [automatic agreement\nreport](../governance/release-check.qmd) compares that registry with the exact\n500-draw simulation controls and records the analysis-code revision.\nThe historical index extract used in the worked calculation is saved as\n[`cmp-historical-indices.csv`](../data/cmp-historical-indices.csv). It was\nextracted from the updated `h1_0.16` assessment output associated with\n`input/0.15.dat`, retaining both Peruvian index series.\nThe main implementation sources are `run_candidate_mps.R` and\n`tune_candidate_change_limits.R` in the analysis revision named in that\nreport.\nIf the data delays, recent-year windows, combined-index calculation, or annual\nchange rule are revised, this page and the MSE tests must be updated together.\n",
    "supporting": [
      "tac-2027_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}